-- A. 

CREATE TABLE ADVENTURE_TRIP (
  TRIP_ID INTEGER PRIMARY KEY,
  TRIP_NAME TEXT,
  START_LOCATION TEXT,
  STATE TEXT,
  DISTANCE INTEGER,
  MAX_GRP_SIZE INTEGER,
  TYPE TEXT,
  SEASON TEXT
);

-- B.

INSERT INTO `ADVENTURE_TRIP` (TRIP_ID, TRIP_NAME, START_LOCATION, STATE, DISTANCE, MAX_GRP_SIZE, TYPE, SEASON)
VALUES('45','Jay Peak','Jay','VT','8','8','Hiking','Summer');

-- C.

DROP TABLE `ADVENTURE_TRIP`;